# Site settings
title: Anime Austin
email: info@animeaustin.com
description: ""
baseurl: ""
url: "http://www.animeaustin.com"
twitter_username: 
facebook_username: AnimeAustin
github_username:  bentsea

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
encoding: utf-8
